### ISSUE TITLE
Execution throws "Class 'PhpParser\ParserFactory' not found"-Exception

### ISSUE THREAD

**Issue by mmaedler** [vitormattos/blueprint-sdk-maker#6]
Hi there, 

I have downloaded the most recent release of the sdk maker and installed on my Ubuntu 16.04 box. However, everytime I execute the following command 

```./blueprint-sdk-maker --no-phar make ../api/api.apib```

The following Exception is thrown:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Class 'PhpParser\ParserFactory' not found
```

Are there any other dependencies that I need to have installed or what am I doing wrong here?

Thanks!

**Comment by vitormattos** [comment]
Hello!

Sorry for delay in response.

I identify bugs in parse with new version of drafter, please test new version of project.

In time, flip command and argument:
./blueprint-sdk-maker make --no-phar ../api/api.apib

if possible, run unity tests in your environment.

**Comment by vitormattos** [comment]
solved.
